# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-10 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_block_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
