# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20170510_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='slug',
            field=models.SlugField(blank=True, help_text='leave this field blank', null=True, unique=True),
        ),
    ]
