# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-10 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20170510_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='remaining_rooms',
            field=models.IntegerField(default=None, help_text='leave this field blank'),
        ),
    ]
